apiVersion: v1
kind: Template
metadata:
  name: snafu
parameters:
- name: SNAFU_IMAGE
  description: Image to deploy
  value: docker.io/appuio/snafu
- name: SNAFU_IMAGE_TAG
  description: Tag of the Snafu Docker Image to deploy
  value: latest
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: snafu
    name: snafu
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${SNAFU_IMAGE}:${SNAFU_IMAGE_TAG}
      importPolicy: {}
      name: ${SNAFU_IMAGE_TAG}
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: snafu
    name: snafu
  spec:
    replicas: 1
    selector:
      app: snafu
      deploymentconfig: snafu
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: snafu
          deploymentconfig: snafu
      spec:
        containers:
        - args:
          - --executor=inmemory
          - --logger=csv
          - --connector=web
          command:
          - /opt/snafu
          - -s
          - /etc/snafu/snafu.ini
          image: snafu
          imagePullPolicy: Always
          name: snafu
          ports:
          - containerPort: 10000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/functions
            name: functions
          - mountPath: /etc/snafu
            name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: functions
          name: functions
        - configMap:
            defaultMode: 420
            name: config
          name: config
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - snafu
        from:
          kind: ImageStreamTag
          name: snafu:${SNAFU_IMAGE_TAG}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: snafu
    name: snafu
  spec:
    ports:
    - name: 10000-tcp
      port: 10000
      protocol: TCP
      targetPort: 10000
    selector:
      app: snafu
      deploymentconfig: snafu
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: snafu
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: snafu
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  data:
    snafu.ini: |
      [snafu]
      logger.csv = /tmp/snafu.csv
      connector.web = 8080
  kind: ConfigMap
  metadata:
    name: config
- apiVersion: v1
  data:
    helloworld.py: "def helloworld():\n\treturn \"Hello, \U0001F310.\"\n"
  kind: ConfigMap
  metadata:
    name: functions
